import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class UIShellModularizationStaticTests(unittest.TestCase):
    def test_style_shell_delegates_design_tokens_to_styles_module(self):
        style_css = (ROOT / "static" / "style.css").read_text(encoding="utf-8")
        tokens_css = (ROOT / "static" / "styles" / "tokens.css").read_text(encoding="utf-8")
        base_css = (ROOT / "static" / "styles" / "base.css").read_text(encoding="utf-8")
        layout_css = (ROOT / "static" / "styles" / "layout.css").read_text(encoding="utf-8")
        components_css = (ROOT / "static" / "styles" / "components.css").read_text(encoding="utf-8")
        model_registry_css = (ROOT / "static" / "styles" / "components" / "model_registry.css").read_text(encoding="utf-8")
        selection_controls_css = (ROOT / "static" / "styles" / "components" / "selection_controls.css").read_text(encoding="utf-8")
        media_preview_css = (ROOT / "static" / "styles" / "components" / "media_preview.css").read_text(encoding="utf-8")
        data_inputs_css = (ROOT / "static" / "styles" / "components" / "data_inputs.css").read_text(encoding="utf-8")
        tooltip_css = (ROOT / "static" / "styles" / "components" / "tooltip.css").read_text(encoding="utf-8")
        dashboard_css = (ROOT / "static" / "styles" / "pages" / "dashboard.css").read_text(encoding="utf-8")
        history_css = (ROOT / "static" / "styles" / "pages" / "history.css").read_text(encoding="utf-8")
        dataset_css = (ROOT / "static" / "styles" / "pages" / "dataset.css").read_text(encoding="utf-8")
        labelme_css = (ROOT / "static" / "styles" / "pages" / "labelme.css").read_text(encoding="utf-8")
        training_css = (ROOT / "static" / "styles" / "pages" / "training.css").read_text(encoding="utf-8")
        rnn_training_css = (ROOT / "static" / "styles" / "pages" / "rnn_training.css").read_text(encoding="utf-8")
        augmentation_css = (ROOT / "static" / "styles" / "pages" / "augmentation.css").read_text(encoding="utf-8")
        model_compare_css = (ROOT / "static" / "styles" / "pages" / "model_compare.css").read_text(encoding="utf-8")
        inference_css = (ROOT / "static" / "styles" / "pages" / "inference.css").read_text(encoding="utf-8")
        auto_labeling_css = (ROOT / "static" / "styles" / "pages" / "auto_labeling.css").read_text(encoding="utf-8")
        evaluation_css = (ROOT / "static" / "styles" / "pages" / "evaluation.css").read_text(encoding="utf-8")
        shared_css = (ROOT / "static" / "styles" / "shared.css").read_text(encoding="utf-8")

        self.assertTrue(
            style_css.startswith(
                '@import "./styles/tokens.css";\n'
                '@import "./styles/base.css";\n'
                '@import "./styles/layout.css";\n'
                '@import "./styles/components.css";\n'
                '@import "./styles/components/model_registry.css";\n'
                '@import "./styles/components/selection_controls.css";\n'
                '@import "./styles/components/media_preview.css";\n'
                '@import "./styles/components/data_inputs.css";\n'
                '@import "./styles/components/tooltip.css";\n'
                '@import "./styles/pages/dashboard.css";\n'
                '@import "./styles/pages/history.css";\n'
                '@import "./styles/pages/dataset.css";\n'
                '@import "./styles/pages/labelme.css";\n'
                '@import "./styles/pages/training.css";\n'
                '@import "./styles/pages/rnn_training.css";\n'
                '@import "./styles/pages/augmentation.css";\n'
                '@import "./styles/pages/model_compare.css";\n'
                '@import "./styles/pages/inference.css";\n'
                '@import "./styles/pages/auto_labeling.css";\n'
                '@import "./styles/pages/evaluation.css";\n'
                '@import "./styles/shared.css";'
            )
        )
        self.assertNotRegex(style_css, r"(?m)^[.#a-zA-Z][^{]+\{")
        self.assertNotIn(":root {\n  --bg:", style_css)
        self.assertNotIn('body[data-theme="light"] {\n  --bg:', style_css)
        self.assertNotIn("html,\nbody {\n  margin: 0;", style_css)
        self.assertNotIn("button,\ninput,\nselect", style_css)
        self.assertNotIn(".app-shell {", style_css)
        self.assertNotIn(".top-header {", style_css)
        self.assertNotIn(".app-body {", style_css)
        self.assertNotIn(".right-summary-panel {", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.btn \{")
        self.assertNotRegex(style_css, r"(?m)^\.badge \{")
        self.assertNotRegex(style_css, r"(?m)^\.global-progress-hud \{")
        self.assertNotRegex(style_css, r"(?m)^\.guard-stack \{")
        self.assertNotRegex(style_css, r"(?m)^\.narrow-form \{")
        self.assertNotRegex(style_css, r"(?m)^\.form-stack \{")
        self.assertNotRegex(style_css, r"(?m)^\.table-wrap \{")
        self.assertNotRegex(style_css, r"(?m)^\.data-table \{")
        self.assertNotRegex(style_css, r"(?m)^\.modal-overlay \{")
        self.assertNotRegex(style_css, r"(?m)^\.modal-content \{")
        self.assertNotRegex(style_css, r"(?m)^\.toast \{")
        self.assertNotRegex(style_css, r"(?m)^\.summary-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.summary-badge \{")
        self.assertNotRegex(style_css, r"(?m)^\.product-state-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-registry-list \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-registry-list\.grouped \{")
        self.assertNotRegex(style_css, r"(?m)^\.weight-manager-modal-content \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-import-supported-types \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-approval-panel \{")
        self.assertNotRegex(style_css, r"(?m)^\.simple-step-list \{")
        self.assertNotRegex(style_css, r"(?m)^\.source-option-grid,")
        self.assertNotRegex(style_css, r"(?m)^\.source-option,")
        self.assertNotRegex(style_css, r"(?m)^\.mode-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.strategy-list \{")
        self.assertNotRegex(style_css, r"(?m)^\.advanced-collapse \{")
        self.assertNotRegex(style_css, r"(?m)^\.preview-tile \{")
        self.assertNotRegex(style_css, r"(?m)^\.thumbnail-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.path-list \{")
        self.assertNotRegex(style_css, r"(?m)^\.path-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.project-context-compact \{")
        self.assertNotRegex(style_css, r"(?m)^\.preview-panel \{")
        self.assertNotRegex(style_css, r"(?m)^\.preview-placeholder \{")
        self.assertNotRegex(style_css, r"(?m)^\.section-help \{")
        self.assertNotRegex(style_css, r"(?m)^\.zip-storage-box \{")
        self.assertNotRegex(style_css, r"(?m)^\.zip-drop-zone \{")
        self.assertNotRegex(style_css, r"(?m)^\.class-entry-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.class-list-box \{")
        self.assertNotRegex(style_css, r"(?m)^\.class-chip \{")
        self.assertNotRegex(style_css, r"(?m)^\.empty-class-list \{")
        self.assertNotRegex(style_css, r"(?m)^\.ingest-progress-container \{")
        self.assertNotRegex(style_css, r"(?m)^\.ingest-progress-bar-bg \{")
        self.assertNotRegex(style_css, r"(?m)^\.info-icon \{")
        self.assertNotRegex(style_css, r"(?m)^\.info-icon::after \{")
        self.assertNotRegex(style_css, r"(?m)^\.floating-tooltip \{")
        self.assertNotRegex(style_css, r"(?m)^\.floating-tooltip\.is-visible \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-map-panel \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.project-history-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.history-filter-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.project-history-modal-content \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-job-cleanup-toolbar,")
        self.assertNotRegex(style_css, r"(?m)^\.migration-candidate-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.dataset-manager-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.dataset-video-fields \{")
        self.assertNotRegex(style_css, r"(?m)^\.dataset-browser-tools \{")
        self.assertNotRegex(style_css, r"(?m)^\.labelme-clean-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.labelme-step-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.labelme-progress-hero \{")
        self.assertNotRegex(style_css, r"(?m)^\.labelme-export-details \{")
        self.assertNotRegex(style_css, r"(?m)^\.annotation-import-report \{")
        self.assertNotRegex(style_css, r"(?m)^\.annotation-import-summary \{")
        self.assertNotRegex(style_css, r"(?m)^\.csv-mapping-wizard \{")
        self.assertNotRegex(style_css, r"(?m)^\.csv-file-mapping \{")
        self.assertNotRegex(style_css, r"(?m)^\.annotation-import-details \{")
        self.assertNotRegex(style_css, r"(?m)^\.annotation-import-report-modal-content \{")
        self.assertNotRegex(style_css, r"(?m)^\.modal-report-table \{")
        self.assertNotRegex(style_css, r"(?m)^\.training-main-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.monitor-grid \{")
        self.assertNotIn("Training Control Console CSS", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.training-mode-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.training-mode-toggle \{")
        self.assertNotRegex(style_css, r"(?m)^\.training-readiness \{")
        self.assertNotRegex(style_css, r"(?m)^\.training-overview-grid \{")
        self.assertNotRegex(style_css, r"(?m)^#config-simple-fields,")
        self.assertNotRegex(style_css, r"(?m)^\.training-start-blocker,")
        self.assertNotRegex(style_css, r"(?m)^\.chart-control-panel \{")
        self.assertNotRegex(style_css, r"(?m)^\.chart-report-container \{")
        self.assertNotRegex(style_css, r"(?m)^\.trend-diagnostic-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.artifact-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.training-scroll-table \{")
        self.assertNotRegex(style_css, r"(?m)^\.rnn-eval-flow \{")
        self.assertNotRegex(style_css, r"(?m)^\.rnn-training-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.rnn-readiness-compact-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.rnn-sequence-test-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.augmentation-workspace \{")
        self.assertNotRegex(style_css, r"(?m)^\.augmentation-settings-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.custom-setting-item \{")
        self.assertNotRegex(style_css, r"(?m)^\.preset-item \{")
        self.assertNotRegex(style_css, r"(?m)^\.aug-preview-container \{")
        self.assertNotIn("Physical Augmentation Redesign Styles", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.model-compare-mode-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.compare-mode-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-compare-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.compare-run-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.compare-output-controls \{")
        self.assertNotIn("Model Compare Center", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.inference-lab-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-settings-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-preview-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-summary-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.auto-label-workbench \{")
        self.assertNotRegex(style_css, r"(?m)^\.auto-job-builder \{")
        self.assertNotRegex(style_css, r"(?m)^\.auto-step-block \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-source-tabs \{")
        self.assertNotRegex(style_css, r"(?m)^\.target-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.review-preview-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.auto-review-workstation \{")
        self.assertNotRegex(style_css, r"(?m)^\.auto-shape-review-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.evaluation-guidance-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.evaluation-plots-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.evaluation-plot-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.evaluation-plot-modal \{")
        self.assertNotIn(".dashboard-lower-grid,\n.two-column-layout", style_css)
        self.assertNotIn("@media (max-width: 840px) {", style_css)

        self.assertIn(":root {", tokens_css)
        self.assertIn("--bg: #0f1318;", tokens_css)
        self.assertIn("--primary: #3b82f6;", tokens_css)
        self.assertIn("--radius: 8px;", tokens_css)
        self.assertIn('body[data-theme="light"] {', tokens_css)
        self.assertIn("--shadow: 0 12px 30px rgba(15, 23, 42, 0.12);", tokens_css)

        self.assertIn("* {\n  box-sizing: border-box;", base_css)
        self.assertIn("html,\nbody {\n  margin: 0;", base_css)
        self.assertIn('font-family: "Inter", "Microsoft JhengHei", "PingFang TC", sans-serif;', base_css)
        self.assertIn("button,\ninput,\nselect", base_css)
        self.assertIn("code {", base_css)
        self.assertNotIn(".app-shell {", base_css)

        self.assertIn(".app-shell {", layout_css)
        self.assertIn("grid-template-rows: 64px 1fr;", layout_css)
        self.assertIn(".top-header {", layout_css)
        self.assertIn(".app-body {", layout_css)
        self.assertIn("grid-template-columns: 250px minmax(0, 1fr) 300px;", layout_css)
        self.assertIn(".sidebar {", layout_css)
        self.assertIn(".main-content {", layout_css)
        self.assertIn(".right-summary-panel {", layout_css)
        self.assertIn(".page-header {", layout_css)
        self.assertNotIn(".btn {", layout_css)

        self.assertRegex(components_css, r"(?m)^\.btn \{")
        self.assertRegex(components_css, r"(?m)^\.icon-btn \{")
        self.assertIn(".panel-section,\n.summary-section,\n.control-card,\n.metric-card,\n.status-guard", components_css)
        self.assertRegex(components_css, r"(?m)^\.badge \{")
        self.assertRegex(components_css, r"(?m)^\.global-progress-hud \{")
        self.assertIn("@keyframes progress-hud-pending", components_css)
        self.assertRegex(components_css, r"(?m)^\.guard-stack \{")
        self.assertRegex(components_css, r"(?m)^\.guard-next-actions \{")
        self.assertRegex(components_css, r"(?m)^\.narrow-form \{")
        self.assertRegex(components_css, r"(?m)^\.form-stack \{")
        self.assertIn('input[type="text"],\ninput[type="number"],\nselect {', components_css)
        self.assertRegex(components_css, r"(?m)^\.table-wrap \{")
        self.assertRegex(components_css, r"(?m)^\.data-table \{")
        self.assertRegex(components_css, r"(?m)^\.modal-overlay \{")
        self.assertRegex(components_css, r"(?m)^\.modal-content \{")
        self.assertRegex(components_css, r"(?m)^\.toast \{")
        self.assertRegex(components_css, r"(?m)^\.summary-row \{")
        self.assertRegex(components_css, r"(?m)^\.summary-badge \{")
        self.assertRegex(components_css, r"(?m)^\.product-state-card \{")
        self.assertNotIn(".dashboard-lower-grid,\n.two-column-layout", components_css)
        self.assertNotRegex(components_css, r"(?m)^\.workflow-card \{")
        self.assertNotRegex(components_css, r"(?m)^\.dataset-manager-layout \{")
        self.assertNotRegex(components_css, r"(?m)^\.labelme-step-card \{")
        self.assertNotRegex(components_css, r"(?m)^\.training-main-grid \{")
        self.assertNotRegex(components_css, r"(?m)^\.augmentation-workspace \{")

        self.assertRegex(model_registry_css, r"(?m)^\.model-registry-list \{")
        self.assertRegex(model_registry_css, r"(?m)^\.model-registry-list\.grouped \{")
        self.assertRegex(model_registry_css, r"(?m)^\.model-registry-scroll \{")
        self.assertRegex(model_registry_css, r"(?m)^\.weight-manager-modal-content \{")
        self.assertRegex(model_registry_css, r"(?m)^\.model-import-supported-types \{")
        self.assertRegex(model_registry_css, r"(?m)^\.model-import-drop-zone \{")
        self.assertRegex(model_registry_css, r"(?m)^\.model-approval-panel \{")
        self.assertIn("@media (max-width: 860px) {", model_registry_css)
        self.assertIn("@media (max-width: 980px) {", model_registry_css)

        self.assertRegex(selection_controls_css, r"(?m)^\.simple-step-list \{")
        self.assertRegex(selection_controls_css, r"(?m)^\.compact-source-grid \{")
        self.assertRegex(selection_controls_css, r"(?m)^\.source-option-grid,")
        self.assertRegex(selection_controls_css, r"(?m)^\.source-option,")
        self.assertRegex(selection_controls_css, r"(?m)^\.mode-card \{")
        self.assertRegex(selection_controls_css, r"(?m)^\.strategy-list \{")
        self.assertRegex(selection_controls_css, r"(?m)^\.advanced-collapse \{")
        self.assertIn("@media (max-width: 840px) {", selection_controls_css)

        self.assertRegex(media_preview_css, r"(?m)^\.preview-tile \{")
        self.assertRegex(media_preview_css, r"(?m)^\.thumbnail-grid \{")
        self.assertRegex(media_preview_css, r"(?m)^\.path-list \{")
        self.assertRegex(media_preview_css, r"(?m)^\.path-row \{")
        self.assertRegex(media_preview_css, r"(?m)^\.project-context-compact \{")
        self.assertRegex(media_preview_css, r"(?m)^\.preview-panel \{")
        self.assertRegex(media_preview_css, r"(?m)^\.preview-placeholder \{")
        self.assertIn("@media (max-width: 840px) {", media_preview_css)

        self.assertRegex(data_inputs_css, r"(?m)^\.section-help \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.zip-storage-box \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.zip-drop-zone \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.class-entry-row \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.class-list-box \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.class-chip \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.empty-class-list \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.ingest-progress-container \{")
        self.assertRegex(data_inputs_css, r"(?m)^\.ingest-progress-bar-bg \{")
        self.assertIn("@media (max-width: 560px) {", data_inputs_css)
        self.assertIn("@media (max-width: 840px) {", data_inputs_css)

        self.assertRegex(tooltip_css, r"(?m)^\.info-icon \{")
        self.assertRegex(tooltip_css, r"(?m)^body\[data-theme=\"light\"\] \.info-icon \{")
        self.assertRegex(tooltip_css, r"(?m)^\.info-icon::after \{")
        self.assertRegex(tooltip_css, r"(?m)^\.floating-tooltip \{")
        self.assertRegex(tooltip_css, r"(?m)^\.floating-tooltip\.is-visible \{")
        self.assertIn(".floating-tooltip.place-right,\n.floating-tooltip.place-left", tooltip_css)

        self.assertRegex(dashboard_css, r"(?m)^#page-dashboard \.dashboard-lower-grid \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-map-panel \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-map-title \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-grid \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-card \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-row \{")
        self.assertIn("@media (max-width: 1500px) {", dashboard_css)
        self.assertIn("@media (max-width: 1180px) {", dashboard_css)

        self.assertRegex(history_css, r"(?m)^\.project-history-card \{")
        self.assertRegex(history_css, r"(?m)^\.project-file-summary \{")
        self.assertRegex(history_css, r"(?m)^\.history-filter-row \{")
        self.assertRegex(history_css, r"(?m)^\.project-history-modal-content \{")
        self.assertRegex(history_css, r"(?m)^\.history-search-row \{")
        self.assertRegex(history_css, r"(?m)^\.inference-history-card \{")
        self.assertRegex(history_css, r"(?m)^\.inference-job-cleanup-toolbar,")
        self.assertRegex(history_css, r"(?m)^\.migration-candidate-card \{")
        self.assertIn("@media (max-width: 760px) {", history_css)

        self.assertRegex(dataset_css, r"(?m)^\.dataset-manager-layout \{")
        self.assertRegex(dataset_css, r"(?m)^\.dataset-manager-layout > \* \{")
        self.assertRegex(dataset_css, r"(?m)^\.dataset-classes-card,")
        self.assertRegex(dataset_css, r"(?m)^\.dataset-video-fields \{")
        self.assertRegex(dataset_css, r"(?m)^\.dataset-browser-header \{")
        self.assertRegex(dataset_css, r"(?m)^\.dataset-browser-tools \{")
        self.assertRegex(dataset_css, r"(?m)^\.dataset-meta-row \{")
        self.assertIn("@media (max-width: 840px) {", dataset_css)

        self.assertRegex(labelme_css, r"(?m)^\.labelme-layout \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-clean-layout \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-step-strip \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-step-card \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-drop-zone \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-path-list \.path-row \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-progress-hero \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-review-table \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-export-details \{")
        self.assertRegex(labelme_css, r"(?m)^\.annotation-import-report \{")
        self.assertRegex(labelme_css, r"(?m)^\.annotation-import-summary \{")
        self.assertRegex(labelme_css, r"(?m)^\.annotation-import-meta \{")
        self.assertRegex(labelme_css, r"(?m)^\.csv-mapping-wizard \{")
        self.assertRegex(labelme_css, r"(?m)^\.csv-file-mapping \{")
        self.assertRegex(labelme_css, r"(?m)^\.csv-map-field \{")
        self.assertRegex(labelme_css, r"(?m)^\.annotation-import-details \{")
        self.assertRegex(labelme_css, r"(?m)^\.annotation-import-report-modal-content \{")
        self.assertRegex(labelme_css, r"(?m)^\.modal-report-table \{")
        self.assertRegex(labelme_css, r"(?m)^\.labelme-conversion-grid \{")
        self.assertNotRegex(labelme_css, r"(?m)^\.zip-drop-zone \{")
        self.assertIn("@media (max-width: 1500px) {", labelme_css)
        self.assertIn("@media (max-width: 840px) {", labelme_css)

        self.assertRegex(training_css, r"(?m)^\.training-main-grid \{")
        self.assertRegex(training_css, r"(?m)^\.training-config-panel,")
        self.assertRegex(training_css, r"(?m)^\.monitor-grid \{")
        self.assertRegex(training_css, r"(?m)^\.monitor-grid \.metric-card \{")
        self.assertIn("Training Control Console CSS", training_css)
        self.assertRegex(training_css, r"(?m)^\.training-mode-layout \{")
        self.assertRegex(training_css, r"(?m)^\.training-mode-toggle \{")
        self.assertRegex(training_css, r"(?m)^\.training-shared-nav,")
        self.assertRegex(training_css, r"(?m)^\.training-readiness \{")
        self.assertRegex(training_css, r"(?m)^\.training-overview-grid \{")
        self.assertRegex(training_css, r"(?m)^#config-simple-fields,")
        self.assertRegex(training_css, r"(?m)^\.training-start-blocker,")
        self.assertRegex(training_css, r"(?m)^\.training-recommendation-card \{")
        self.assertRegex(training_css, r"(?m)^\.chart-control-panel \{")
        self.assertRegex(training_css, r"(?m)^\.chart-report-container \{")
        self.assertRegex(training_css, r"(?m)^\.metric-progress \{")
        self.assertRegex(training_css, r"(?m)^\.trend-diagnostic-card \{")
        self.assertRegex(training_css, r"(?m)^\.artifact-row \{")
        self.assertRegex(training_css, r"(?m)^\.training-scroll-table \{")
        self.assertIn("@media (max-width: 840px) {", training_css)
        self.assertIn("@media (max-width: 760px) {", training_css)
        self.assertIn("@media (max-width: 980px) {", training_css)
        self.assertIn("@media (max-width: 1100px) {", training_css)

        self.assertRegex(rnn_training_css, r"(?m)^\.rnn-eval-flow \{")
        self.assertRegex(rnn_training_css, r"(?m)^\.rnn-training-layout \{")
        self.assertRegex(rnn_training_css, r"(?m)^\.rnn-readiness-compact-grid \{")
        self.assertRegex(rnn_training_css, r"(?m)^\.rnn-sequence-test-layout \{")
        self.assertRegex(rnn_training_css, r"(?m)^\.training-rnn-header-actions \{")
        self.assertIn("@media (max-width: 840px) {", rnn_training_css)
        self.assertIn("@media (max-width: 980px) {", rnn_training_css)
        self.assertIn("@media (max-width: 1100px) {", rnn_training_css)

        self.assertRegex(augmentation_css, r"(?m)^\.augmentation-workspace \{")
        self.assertRegex(augmentation_css, r"(?m)^\.augmentation-settings-layout \{")
        self.assertRegex(augmentation_css, r"(?m)^\.custom-setting-item \{")
        self.assertRegex(augmentation_css, r"(?m)^\.preset-item \{")
        self.assertRegex(augmentation_css, r"(?m)^\.aug-preview-container \{")
        self.assertIn("Physical Augmentation Redesign Styles", augmentation_css)
        self.assertIn("@media (max-width: 840px) {", augmentation_css)

        self.assertIn("Model Compare Center", model_compare_css)
        self.assertRegex(model_compare_css, r"(?m)^\.model-compare-mode-card \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-mode-row \{")
        self.assertRegex(model_compare_css, r"(?m)^\.model-compare-layout \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-run-card \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-output-controls \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-report-history-card \{")
        self.assertIn("@media (max-width: 840px) {", model_compare_css)

        self.assertRegex(inference_css, r"(?m)^\.inference-lab-grid \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-settings-grid \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-toggle-row \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-result-panel \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-preview-grid \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-summary-grid \{")
        self.assertNotRegex(inference_css, r"(?m)^\.preview-tile \{")
        self.assertIn("@media (max-width: 840px) {", inference_css)

        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-label-layout \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-label-status-strip \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-label-workbench \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-job-builder \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-step-block \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.model-source-tabs \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.target-card \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.review-preview-grid \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-review-workstation \{")
        self.assertRegex(auto_labeling_css, r"(?m)^\.auto-shape-review-grid \{")
        self.assertIn("@media (max-width: 1600px) {", auto_labeling_css)
        self.assertIn("@media (max-width: 840px) {", auto_labeling_css)

        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-guidance-grid \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-guidance-item \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-plots-grid \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-metric-grid \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-plot-card \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-plot-download \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-plot-preview \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-plot-modal \{")
        self.assertRegex(evaluation_css, r"(?m)^\.evaluation-wide-empty \{")
        self.assertIn("@media (max-width: 1280px) {", evaluation_css)

        self.assertIn(".dashboard-lower-grid,\n.two-column-layout", shared_css)
        self.assertRegex(shared_css, r"(?m)^\.compact-table \{")
        self.assertRegex(shared_css, r"(?m)^\.settings-controls \{")
        self.assertRegex(shared_css, r"(?m)^input\[type=\"range\"\] \{")
        self.assertRegex(shared_css, r"(?m)^\.inline-fields,")
        self.assertRegex(shared_css, r"(?m)^\.split-ratio-total \{")
        self.assertRegex(shared_css, r"(?m)^\.phase-card \{")
        self.assertRegex(shared_css, r"(?m)^\.btn\.success \{")
        self.assertRegex(shared_css, r"(?m)^\.auto-settings-grid \{")
        self.assertRegex(shared_css, r"(?m)^\.checkbox-row \{")
        self.assertRegex(shared_css, r"(?m)^\.list-stack,")
        self.assertRegex(shared_css, r"(?m)^\.empty-state \{")
        self.assertRegex(shared_css, r"(?m)^body\[data-theme=\"light\"\] \.empty-state \{")
        self.assertRegex(shared_css, r"(?m)^\.workflow-list \{")
        self.assertRegex(shared_css, r"(?m)^\.next-actions \{")
        self.assertRegex(shared_css, r"(?m)^\.hidden \{")
        self.assertIn("@media (max-width: 840px) {", shared_css)

    def test_state_shell_delegates_i18n_dictionary_and_fallback_to_state_module(self):
        state_js = (ROOT / "static" / "state.js").read_text(encoding="utf-8")
        i18n_js = (ROOT / "static" / "state" / "i18n.js").read_text(encoding="utf-8")
        zh_tw_js = (ROOT / "static" / "state" / "i18n" / "zh-TW.js").read_text(encoding="utf-8")
        en_js = (ROOT / "static" / "state" / "i18n" / "en.js").read_text(encoding="utf-8")

        self.assertIn('from "./state/i18n.js"', state_js)
        self.assertIn('export { i18n } from "./state/i18n.js";', state_js)
        self.assertIn("return translateI18n(key, appState.settings.language, params);", state_js)
        self.assertIn("applyLanguageToDocument({", state_js)
        self.assertNotIn("export const i18n = {", state_js)
        self.assertNotIn("let zhFallbackObserver", state_js)
        self.assertNotIn("configureI18nFallback", state_js)

        self.assertIn('import { zhTW } from "./i18n/zh-TW.js";', i18n_js)
        self.assertIn('import { en } from "./i18n/en.js";', i18n_js)
        self.assertIn("export const i18n = {", i18n_js)
        self.assertIn('"zh-TW": zhTW,', i18n_js)
        self.assertIn("  en,", i18n_js)
        self.assertIn("export function translate", i18n_js)
        self.assertIn("export function applyLanguageToDocument", i18n_js)
        self.assertIn("let zhFallbackObserver", i18n_js)
        self.assertIn("configureI18nFallback", i18n_js)
        self.assertNotIn("themeToggle: \"Light\"", i18n_js)
        self.assertNotIn("\"compare.toast.downloadFailed\"", i18n_js)

        self.assertIn("export const zhTW = {", zh_tw_js)
        self.assertIn("themeToggle:", zh_tw_js)
        self.assertIn("\"compare.toast.downloadFailed\"", zh_tw_js)
        self.assertNotIn("export function translate", zh_tw_js)

        self.assertIn("export const en = {", en_js)
        self.assertIn('themeToggle: "Light"', en_js)
        self.assertIn("\"compare.toast.downloadFailed\"", en_js)
        self.assertNotIn("export function translate", en_js)

    def test_training_mode_shell_delegates_state_to_state_module(self):
        training_modes_js = (ROOT / "static" / "pages" / "training_modes.js").read_text(encoding="utf-8")
        training_mode_state_js = (
            ROOT / "static" / "pages" / "training_mode_state.js"
        ).read_text(encoding="utf-8")
        rnn_metric_helpers_js = (
            ROOT / "static" / "pages" / "rnn_metric_helpers.js"
        ).read_text(encoding="utf-8")

        self.assertIn('import { trainingModeState } from "./training_mode_state.js";', training_modes_js)
        self.assertIn('export { trainingModeState } from "./training_mode_state.js";', training_modes_js)
        self.assertIn('} from "./rnn_metric_helpers.js";', training_modes_js)
        self.assertNotIn("export const trainingModeState = {", training_modes_js)
        self.assertIn("export const trainingModeState = {", training_mode_state_js)
        self.assertIn('activeMode: "cnn"', training_mode_state_js)
        self.assertIn('backend: "ultralytics_yolo"', training_mode_state_js)
        self.assertIn('backend: "pytorch_lstm"', training_mode_state_js)
        self.assertIn('comparisonMetric: "macro_f1"', training_mode_state_js)
        self.assertIn("export function resolveComparisonMetricConfig", rnn_metric_helpers_js)
        self.assertIn("export function buildSparklinePoints", rnn_metric_helpers_js)
        self.assertIn("export function sequenceBackendDisplayLabel", rnn_metric_helpers_js)
        self.assertIn('return resolveComparisonMetricConfig(metricKey);', training_modes_js)
        self.assertIn("return buildSparklinePoints(values);", training_modes_js)
        self.assertNotIn("const configs = {\n    accuracy:", training_modes_js)

    def test_app_shell_delegates_common_shell_rendering_to_core_modules(self):
        app_js = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
        bootstrap_js = (ROOT / "static" / "core" / "bootstrap.js").read_text(encoding="utf-8")
        header_js = (ROOT / "static" / "core" / "header_status.js").read_text(encoding="utf-8")
        guards_js = (ROOT / "static" / "core" / "page_guards.js").read_text(encoding="utf-8")
        availability_js = (ROOT / "static" / "core" / "action_availability.js").read_text(encoding="utf-8")
        toast_js = (ROOT / "static" / "core" / "toast.js").read_text(encoding="utf-8")
        router_js = (ROOT / "static" / "core" / "router.js").read_text(encoding="utf-8")
        right_panel_js = (ROOT / "static" / "core" / "right_panel.js").read_text(encoding="utf-8")
        page_registry_js = (ROOT / "static" / "core" / "page_registry.js").read_text(encoding="utf-8")
        tooltip_js = (ROOT / "static" / "core" / "tooltip.js").read_text(encoding="utf-8")
        project_lifecycle_js = (ROOT / "static" / "core" / "project_lifecycle.js").read_text(encoding="utf-8")

        self.assertIn('import { bootstrapApp } from "./core/bootstrap.js";', app_js)
        self.assertIn("bootstrapApp().catch", app_js)
        self.assertNotIn("bindGlobalNavigation", app_js)
        self.assertNotIn("function navigate", app_js)
        self.assertNotIn("function renderAll", app_js)
        self.assertNotIn("createProjectLifecycle", app_js)

        self.assertIn('from "./header_status.js"', bootstrap_js)
        self.assertIn('from "./page_guards.js"', bootstrap_js)
        self.assertIn('from "./action_availability.js"', bootstrap_js)
        self.assertIn('from "./toast.js"', bootstrap_js)
        self.assertIn('from "./router.js"', bootstrap_js)
        self.assertIn('from "./right_panel.js"', bootstrap_js)
        self.assertIn('from "./tooltip.js"', bootstrap_js)
        self.assertIn('from "./project_lifecycle.js"', bootstrap_js)
        self.assertIn('from "./page_registry.js"', bootstrap_js)
        self.assertIn("createProjectLifecycle({ renderAll, navigate });", bootstrap_js)
        self.assertIn("export async function bootstrapApp()", bootstrap_js)
        self.assertIn("initPageModules();", bootstrap_js)
        self.assertIn("initInfoTooltips();", bootstrap_js)
        self.assertIn("function bindGlobalNavigation()", bootstrap_js)
        self.assertIn("renderHeaderStatusCore();", bootstrap_js)
        self.assertIn("renderPrimaryPageModules(status);", bootstrap_js)
        self.assertIn("renderRightPanelCore(appState.currentPage, status);", bootstrap_js)
        self.assertIn("renderPageGuardsCore(appState.currentPage, status);", bootstrap_js)
        self.assertIn("renderSecondaryPageModules(status);", bootstrap_js)
        self.assertIn("updateActionAvailabilityCore(status);", bootstrap_js)
        self.assertIn("showToastCore(message);", bootstrap_js)
        self.assertIn("setActivePage(pageId);", bootstrap_js)
        self.assertNotIn('from "./pages/dashboard.js"', app_js)
        self.assertNotIn('from "./pages/training.js', app_js)
        self.assertNotIn("async function bootstrapSession", app_js)
        self.assertNotIn("async function loadProjects", app_js)
        self.assertNotIn("async function openProject", app_js)
        self.assertNotIn("async function saveCurrentProject", app_js)
        self.assertNotIn("async function requestProjectSave", app_js)
        self.assertNotIn("async function checkCurrentTrainStatus", app_js)
        self.assertNotIn("function renderHeaderStatus()", app_js)
        self.assertNotIn("function renderRightPanel(pageId, status)", app_js)
        self.assertNotIn("const RIGHT_PANEL_CONFIG", app_js)
        self.assertNotIn("function renderPageGuards(pageId, status)", app_js)
        self.assertNotIn("function updateActionAvailability(status)", app_js)
        self.assertNotIn("function showToast(message)", app_js)
        self.assertNotIn("function bindInfoTooltips()", app_js)
        self.assertNotIn("renderTooltipContent", app_js)

        self.assertIn("export function renderHeaderStatus", header_js)
        self.assertIn("#header-gpu-value", header_js)
        self.assertIn("#header-project-title", header_js)

        self.assertIn("export function renderPageGuards", guards_js)
        self.assertIn("isRnnTrainingWorkspaceActive(pageId)", guards_js)
        self.assertIn("Training blocked", guards_js)

        self.assertIn("export function updateActionAvailability", availability_js)
        self.assertIn('qsa(".guarded")', availability_js)
        self.assertIn("#btn-start-train", availability_js)

        self.assertIn("export function showToast", toast_js)
        self.assertIn("#toast", toast_js)
        self.assertIn("window.setTimeout", toast_js)

        self.assertIn("export function setActivePage", router_js)
        self.assertIn('qsa(".sidebar-item")', router_js)
        self.assertIn('qsa(".page")', router_js)
        self.assertIn('pageId || "dashboard"', router_js)

        self.assertIn("export function renderRightPanel", right_panel_js)
        self.assertIn("const RIGHT_PANEL_CONFIG", right_panel_js)
        self.assertIn("function buildRnnTrainingRightPanel", right_panel_js)
        self.assertIn("RNN Context", right_panel_js)

        self.assertIn("export function initPageModules", page_registry_js)
        self.assertIn("export function renderPrimaryPageModules", page_registry_js)
        self.assertIn("export function renderSecondaryPageModules", page_registry_js)
        self.assertIn("export function syncPageModeForProject", page_registry_js)
        self.assertIn("export function loadPageRecommendedConfig", page_registry_js)
        self.assertIn("renderDashboard(status);", page_registry_js)
        self.assertIn("renderTrainingWorkspace();", page_registry_js)

        self.assertIn("export function initInfoTooltips", tooltip_js)
        self.assertIn("#floating-tooltip", tooltip_js)
        self.assertIn(".info-icon[data-tooltip]", tooltip_js)
        self.assertIn("escapeHtml", tooltip_js)
        self.assertIn('window.addEventListener("resize"', tooltip_js)

        self.assertIn("export function createProjectLifecycle", project_lifecycle_js)
        self.assertIn("async function bootstrapSession", project_lifecycle_js)
        self.assertIn("async function loadProjects", project_lifecycle_js)
        self.assertIn("async function openProject", project_lifecycle_js)
        self.assertIn("async function saveCurrentProject", project_lifecycle_js)
        self.assertIn("async function requestProjectSave", project_lifecycle_js)
        self.assertIn("async function checkCurrentTrainStatus", project_lifecycle_js)
        self.assertIn("showToastCore(`Failed to load projects: ${err.message}`);", project_lifecycle_js)
        self.assertIn("syncPageModeForProject(appState.currentProject", project_lifecycle_js)
        self.assertIn("await loadPageRecommendedConfig();", project_lifecycle_js)
        self.assertIn("clearDeletedProject", project_lifecycle_js)


if __name__ == "__main__":
    unittest.main()
