import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class RNNTrainingPageStaticTests(unittest.TestCase):
    def test_rnn_training_controls_expose_p1_hardening_fields(self):
        index_html = (ROOT / "static" / "index.html").read_text(encoding="utf-8")
        training_modes_js = (ROOT / "static" / "pages" / "training_modes.js").read_text(encoding="utf-8")
        rnn_metric_helpers_js = (
            ROOT / "static" / "pages" / "rnn_metric_helpers.js"
        ).read_text(encoding="utf-8")
        training_js = (ROOT / "static" / "pages" / "training.js").read_text(encoding="utf-8")
        right_panel_js = (ROOT / "static" / "core" / "right_panel.js").read_text(encoding="utf-8")
        page_guards_js = (ROOT / "static" / "core" / "page_guards.js").read_text(encoding="utf-8")

        self.assertIn('id="rnn-model-info-icon"', index_html)
        self.assertIn('id="rnn-gradient-clip"', index_html)
        self.assertIn('id="rnn-early-stopping-patience"', index_html)
        self.assertIn('id="rnn-eval-primary-history-label"', index_html)
        self.assertIn('id="rnn-eval-secondary-history-label"', index_html)
        self.assertIn('class="rnn-eval-flow"', index_html)
        self.assertIn('id="rnn-eval-chart-stack"', index_html)
        self.assertIn('id="rnn-eval-baseline-note"', index_html)
        self.assertIn('id="rnn-eval-compare-chart"', index_html)
        self.assertIn('data-rnn-compare-metric="accuracy"', index_html)
        self.assertIn('data-rnn-compare-metric="macro_f1"', index_html)
        self.assertIn('data-rnn-compare-metric="val_loss"', index_html)
        self.assertIn('class="rnn-result-table-wrap rnn-table-scroll-10"', index_html)
        self.assertIn('id="section-rnn-eval-summary"', index_html)
        self.assertIn('id="rnn-eval-sidebar-artifacts"', index_html)
        self.assertIn('id="rnn-readiness-compact-grid"', index_html)
        self.assertIn('id="rnn-readiness-details"', index_html)
        self.assertIn('class="rnn-training-layout"', index_html)
        self.assertIn('class="rnn-preview-card rnn-training-config-section"', index_html)
        self.assertIn('class="rnn-preview-card rnn-custom-model-section"', index_html)
        self.assertIn('class="rnn-preview-card rnn-training-output-section"', index_html)
        self.assertIn('LSTM Classifier</option>', index_html)
        self.assertNotIn('Loading model catalog...</option>', index_html)
        self.assertIn('data-rnn-nav="evaluation"', index_html)
        self.assertIn('data-rnn-nav="sequence-test"', index_html)
        self.assertIn('data-rnn-nav="export"', index_html)
        self.assertNotIn('id="rnn-eval-sidebar-settings"', index_html)

        self.assertIn("gradient_clip_norm", training_modes_js)
        self.assertIn("early_stopping_patience", training_modes_js)
        self.assertIn("CSV must include sequence id", training_modes_js)
        self.assertIn("function getTrainableTemplateRnnCatalog", training_modes_js)
        self.assertIn('model.source !== "project_trained"', training_modes_js)
        self.assertIn("FastRNN Classifier", training_modes_js)
        self.assertIn("Isolation Forest Baseline", training_modes_js)
        self.assertIn("pytorch_fastrnn", training_modes_js)
        self.assertIn("sklearn_isolation_forest", training_modes_js)
        self.assertIn("Loading catalog in background", training_modes_js)
        self.assertNotIn('select.innerHTML = `<option value="">Loading model catalog...</option>`', training_modes_js)
        self.assertIn("await loadRnnModelCatalog({ force: options.force });", training_modes_js)
        self.assertIn("Sequence CSV is ready for RNN training", training_modes_js)
        self.assertIn("rnn-eval-primary-history-label", training_modes_js)
        self.assertIn("function renderRnnMetricTrendRows", training_modes_js)
        self.assertIn("function renderRnnBaselineComparison", training_modes_js)
        self.assertIn("comparisonMetric", training_modes_js)
        self.assertIn("function getComparisonMetricConfig", training_modes_js)
        self.assertIn('"val/accuracy"', rnn_metric_helpers_js)
        self.assertIn('"val/macro_f1"', rnn_metric_helpers_js)
        self.assertIn('"val/loss"', rnn_metric_helpers_js)
        self.assertIn("Single-point baseline", training_modes_js)
        self.assertIn("function renderRnnEvaluationSidebar", training_modes_js)
        self.assertIn("toggleRnnEvaluationRightPanel", training_modes_js)
        self.assertNotIn('renderRnnSidebarRows("#rnn-eval-sidebar-settings"', training_modes_js)
        self.assertIn("XGBoost Classifier is a strong tabular baseline", training_modes_js)
        self.assertIn("export function isRnnTrainingWorkspaceActive", training_modes_js)
        self.assertIn("const firstReady = models.find((model) => model.status === \"ready\");", training_modes_js)
        self.assertIn("select.value = (firstReady || models[0])?.model_id || \"\";", training_modes_js)
        self.assertIn("function syncRnnInferencePathInput", training_modes_js)
        self.assertIn("Local CSV path disabled (Trusted Local Mode off)", training_modes_js)
        self.assertIn("Upload a CSV feature sequence file.", training_modes_js)
        self.assertIn('const hidePageGuards = visible || (appState.currentPage === "training" && trainingModeState.activeMode === "rnn");', training_modes_js)
        self.assertIn("buildRnnTrainingRightPanel", right_panel_js)
        self.assertIn("RNN Context", right_panel_js)
        self.assertIn("isRnnTrainingWorkspaceActive(pageId)", page_guards_js)
        self.assertIn("section.style.display = \"none\";", page_guards_js)
        self.assertIn("function isRnnRegressionMetrics", training_js)
        self.assertIn('isRegression ? "MAE" : "Accuracy"', training_js)
        self.assertIn('isRegression ? "Regression" : "Classification"', training_js)

    def test_rnn_evaluation_layout_has_vertical_chart_and_scroll_table_rules(self):
        style_css = (ROOT / "static" / "styles" / "pages" / "rnn_training.css").read_text(encoding="utf-8")

        self.assertIn(".rnn-eval-flow", style_css)
        self.assertIn("grid-template-columns: minmax(0, 1fr);", style_css)
        self.assertIn(".rnn-eval-chart-stack", style_css)
        self.assertIn(".rnn-baseline-note", style_css)
        self.assertIn(".rnn-compare-mini-chart", style_css)
        self.assertIn(".rnn-compare-metric-toggle", style_css)
        self.assertIn(".rnn-compare-mini-row", style_css)
        self.assertIn(".rnn-compare-mini-row.is-missing", style_css)
        self.assertIn(".rnn-training-layout", style_css)
        self.assertIn(".rnn-training-secondary-grid", style_css)
        self.assertIn(".rnn-output-handoff-grid", style_css)
        self.assertIn("@media (max-width: 840px)", style_css)
        self.assertIn(".rnn-training-config-section", style_css)
        self.assertIn(".rnn-custom-model-section", style_css)
        self.assertIn("grid-template-columns: minmax(0, 1fr);", style_css)
        self.assertIn(".rnn-readiness-compact-grid", style_css)
        self.assertIn(".rnn-readiness-details", style_css)
        self.assertIn(".rnn-table-scroll-10", style_css)
        self.assertIn("max-height: 452px", style_css)
        self.assertIn("position: sticky", style_css)


if __name__ == "__main__":
    unittest.main()
