import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class RNNTrainingPageStaticTests(unittest.TestCase):
    def test_rnn_training_controls_expose_p1_hardening_fields(self):
        index_html = (ROOT / "static" / "index.html").read_text(encoding="utf-8")
        training_modes_js = (ROOT / "static" / "pages" / "training_modes.js").read_text(encoding="utf-8")
        rnn_metric_helpers_js = (
            ROOT / "static" / "pages" / "rnn_metric_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_evaluation_helpers_js = (
            ROOT / "static" / "pages" / "rnn_evaluation_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_artifact_helpers_js = (
            ROOT / "static" / "pages" / "rnn_artifact_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_model_catalog_helpers_js = (
            ROOT / "static" / "pages" / "rnn_model_catalog_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_inference_helpers_js = (
            ROOT / "static" / "pages" / "rnn_inference_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_readiness_helpers_js = (
            ROOT / "static" / "pages" / "rnn_readiness_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_training_payload_helpers_js = (
            ROOT / "static" / "pages" / "rnn_training_payload_helpers.js"
        ).read_text(encoding="utf-8")
        rnn_config_view_helpers_js = (
            ROOT / "static" / "pages" / "rnn_config_view_helpers.js"
        ).read_text(encoding="utf-8")
        training_js = (ROOT / "static" / "pages" / "training.js").read_text(encoding="utf-8")
        right_panel_js = (ROOT / "static" / "core" / "right_panel.js").read_text(encoding="utf-8")
        page_guards_js = (ROOT / "static" / "core" / "page_guards.js").read_text(encoding="utf-8")

        self.assertIn('id="rnn-model-info-icon"', index_html)
        self.assertIn('id="rnn-gradient-clip"', index_html)
        self.assertIn('id="rnn-early-stopping-patience"', index_html)
        self.assertIn('id="rnn-eval-primary-history-label"', index_html)
        self.assertIn('id="rnn-eval-secondary-history-label"', index_html)
        self.assertIn('class="rnn-eval-flow"', index_html)
        self.assertIn('id="rnn-eval-chart-stack"', index_html)
        self.assertIn('id="rnn-eval-baseline-note"', index_html)
        self.assertIn('id="rnn-eval-compare-chart"', index_html)
        self.assertIn('data-rnn-compare-metric="accuracy"', index_html)
        self.assertIn('data-rnn-compare-metric="macro_f1"', index_html)
        self.assertIn('data-rnn-compare-metric="val_loss"', index_html)
        self.assertIn('class="rnn-result-table-wrap rnn-table-scroll-10"', index_html)
        self.assertIn('id="section-rnn-eval-summary"', index_html)
        self.assertIn('id="rnn-eval-sidebar-artifacts"', index_html)
        self.assertIn('id="rnn-readiness-compact-grid"', index_html)
        self.assertIn('id="rnn-readiness-details"', index_html)
        self.assertIn('class="rnn-training-layout"', index_html)
        self.assertIn('class="rnn-preview-card rnn-training-config-section"', index_html)
        self.assertIn('class="rnn-preview-card rnn-custom-model-section"', index_html)
        self.assertIn('class="rnn-preview-card rnn-training-output-section"', index_html)
        self.assertIn('LSTM Classifier</option>', index_html)
        self.assertNotIn('Loading model catalog...</option>', index_html)
        self.assertIn('data-rnn-nav="evaluation"', index_html)
        self.assertIn('data-rnn-nav="sequence-test"', index_html)
        self.assertIn('data-rnn-nav="export"', index_html)
        self.assertNotIn('id="rnn-eval-sidebar-settings"', index_html)

        self.assertIn("export function buildRnnTrainingPayload", rnn_training_payload_helpers_js)
        self.assertIn("buildRnnTrainingPayload({", training_modes_js)
        self.assertIn("gradient_clip_norm", rnn_training_payload_helpers_js)
        self.assertIn("early_stopping_patience", rnn_training_payload_helpers_js)
        self.assertIn('bidirectional: model === "bilstm"', rnn_training_payload_helpers_js)
        self.assertIn("epochs: numberOrDefault(formValues.epochs, 10)", rnn_training_payload_helpers_js)
        self.assertNotIn("const configData = {", training_modes_js)
        self.assertNotIn('Number(qs("#rnn-epochs")', training_modes_js)
        self.assertNotIn('bidirectional: model === "bilstm"', training_modes_js)
        self.assertIn("export function buildRnnDatasetBadge", rnn_config_view_helpers_js)
        self.assertIn("export function resolveRnnFeatureDimension", rnn_config_view_helpers_js)
        self.assertIn("export function formatRnnFeatureConfigHash", rnn_config_view_helpers_js)
        self.assertIn("export function buildRnnPreviewTableModel", rnn_config_view_helpers_js)
        self.assertIn("export function buildRnnFeatureChipModels", rnn_config_view_helpers_js)
        self.assertIn("export function resolveRnnWindowSummary", rnn_config_view_helpers_js)
        self.assertIn("export function buildRnnWindowSummaryRows", rnn_config_view_helpers_js)
        self.assertIn("export function buildRnnMismatchSummary", rnn_config_view_helpers_js)
        self.assertIn("buildRnnDatasetBadge({", training_modes_js)
        self.assertIn("resolveRnnFeatureDimension({ config, inspection })", training_modes_js)
        self.assertIn("formatRnnFeatureConfigHash(config)", training_modes_js)
        self.assertIn("buildRnnPreviewTableModel({", training_modes_js)
        self.assertIn("buildRnnFeatureChipModels({", training_modes_js)
        self.assertIn("buildRnnWindowSummaryRows(windowSummary)", training_modes_js)
        self.assertIn("buildRnnMismatchSummary(trainingModeState.rnn.configMismatches)", training_modes_js)
        self.assertNotIn('files.length ? "badge-success" : "badge-warning"', training_modes_js)
        self.assertNotIn("(config.feature_columns || []).length || inspection.feature_dim || 0", training_modes_js)
        self.assertNotIn("headers.slice(0, 8)", training_modes_js)
        self.assertNotIn("validationStatus.get(name)?.exists ?? headers.has(name)", training_modes_js)
        self.assertNotIn('const estimated = windowSummary.estimated_windows ?? "--";', training_modes_js)
        self.assertNotIn("const mismatches = trainingModeState.rnn.configMismatches || [];", training_modes_js)
        self.assertIn("CSV must include sequence id", training_modes_js)
        self.assertIn("function getTrainableTemplateRnnCatalog", training_modes_js)
        self.assertIn('model.source !== "project_trained"', rnn_model_catalog_helpers_js)
        self.assertIn("FastRNN Classifier", rnn_model_catalog_helpers_js)
        self.assertIn("Isolation Forest Baseline", rnn_model_catalog_helpers_js)
        self.assertIn("pytorch_fastrnn", rnn_model_catalog_helpers_js)
        self.assertIn("sklearn_isolation_forest", rnn_model_catalog_helpers_js)
        self.assertIn("Loading catalog in background", training_modes_js)
        self.assertNotIn('select.innerHTML = `<option value="">Loading model catalog...</option>`', training_modes_js)
        self.assertIn("await loadRnnModelCatalog({ force: options.force });", training_modes_js)
        self.assertIn("Sequence CSV is ready for RNN training", training_modes_js)
        self.assertIn("RNNBackend MVP requires ready CSV feature sequence files", rnn_readiness_helpers_js)
        self.assertIn("CSV must include train and val split rows.", rnn_readiness_helpers_js)
        self.assertIn("parseRnnFeatureColumns(qs(\"#rnn-feature-columns\")?.value || \"\")", training_modes_js)
        self.assertIn("rnn-eval-primary-history-label", training_modes_js)
        self.assertIn("function renderRnnMetricTrendRows", training_modes_js)
        self.assertIn("function renderRnnBaselineComparison", training_modes_js)
        self.assertIn("comparisonMetric", training_modes_js)
        self.assertIn("buildRnnArtifactViewModels", training_modes_js)
        self.assertIn("export const RNN_ARTIFACT_PRIORITY", rnn_artifact_helpers_js)
        self.assertIn("export function sortRnnArtifacts", rnn_artifact_helpers_js)
        self.assertIn("export function formatRnnArtifactSize", rnn_artifact_helpers_js)
        self.assertIn("export function buildRnnArtifactDownloadUrl", rnn_artifact_helpers_js)
        self.assertIn("export function buildRnnArtifactViewModels", rnn_artifact_helpers_js)
        self.assertNotIn("const priority = [\"best.pt\"", training_modes_js)
        self.assertNotIn("Number(artifact.size) / 1024", training_modes_js)
        self.assertNotIn("/artifacts/download/${encodeURIComponent(filename)}", training_modes_js)
        self.assertIn("export function buildRnnBaselineComparisonRows", rnn_evaluation_helpers_js)
        self.assertIn("export function resolveRnnEvaluationViewModel", rnn_evaluation_helpers_js)
        self.assertIn("export function buildRnnEvaluationEpochRows", rnn_evaluation_helpers_js)
        self.assertIn("export function buildRnnEvaluationRunHistoryRows", rnn_evaluation_helpers_js)
        self.assertIn("export function buildRnnMetricTrendRows", rnn_evaluation_helpers_js)
        self.assertIn("export function buildRnnEvaluationSidebarSections", rnn_evaluation_helpers_js)
        self.assertIn("buildSparklinePoints(values)", rnn_evaluation_helpers_js)
        self.assertIn("buildRnnEvaluationEpochRows(history)", training_modes_js)
        self.assertIn("buildRnnEvaluationRunHistoryRows(runs)", training_modes_js)
        self.assertIn("buildRnnMetricTrendRows({ history, isRegression, metricContext })", training_modes_js)
        self.assertIn("buildRnnEvaluationSidebarSections({", training_modes_js)
        self.assertIn("dataset.split_counts || readiness.split_counts", rnn_evaluation_helpers_js)
        self.assertIn("sequenceBackendDisplayLabel(activeRun || metrics || {})", rnn_evaluation_helpers_js)
        self.assertNotIn('row["val/accuracy"] ?? row["val/mae"]', training_modes_js)
        self.assertNotIn("run.primary_metric_name ||", training_modes_js)
        self.assertNotIn('run.status === "completed" ? "badge-success" : "badge-warning"', training_modes_js)
        self.assertNotIn("dataset.split_counts || readiness.split_counts", training_modes_js)
        self.assertNotIn("const modelLabel = activeRun?.model", training_modes_js)
        self.assertNotIn("[primary.label, formatRnnMetric(primary.value)]", training_modes_js)
        self.assertNotIn("const charts = isRegression", training_modes_js)
        self.assertNotIn("function metricSeries", training_modes_js)
        self.assertNotIn("function sparklinePoints", training_modes_js)
        self.assertNotIn("function getComparisonMetricConfig", training_modes_js)
        self.assertIn('"val/accuracy"', rnn_metric_helpers_js)
        self.assertIn('"val/macro_f1"', rnn_metric_helpers_js)
        self.assertIn('"val/loss"', rnn_metric_helpers_js)
        self.assertIn("resolveComparisonMetricConfig(metricKey)", rnn_evaluation_helpers_js)
        self.assertIn("resolveRunComparisonMetric(run, metrics, metricConfig)", rnn_evaluation_helpers_js)
        self.assertIn("Single-point baseline", training_modes_js)
        self.assertIn("function renderRnnEvaluationSidebar", training_modes_js)
        self.assertIn("toggleRnnEvaluationRightPanel", training_modes_js)
        self.assertNotIn('renderRnnSidebarRows("#rnn-eval-sidebar-settings"', training_modes_js)
        self.assertIn("XGBoost Classifier is a strong tabular baseline", rnn_model_catalog_helpers_js)
        self.assertIn("export function isRnnTrainingWorkspaceActive", training_modes_js)
        self.assertIn("const firstReady = models.find((model) => model.status === \"ready\");", rnn_inference_helpers_js)
        self.assertIn("return (firstReady || models[0])?.model_id || \"\";", rnn_inference_helpers_js)
        self.assertIn("function syncRnnInferencePathInput", training_modes_js)
        self.assertIn("Local CSV path disabled (Trusted Local Mode off)", training_modes_js)
        self.assertIn("Upload a CSV feature sequence file.", rnn_inference_helpers_js)
        self.assertIn('const hidePageGuards = visible || (appState.currentPage === "training" && trainingModeState.activeMode === "rnn");', training_modes_js)
        self.assertIn("buildRnnTrainingRightPanel", right_panel_js)
        self.assertIn("RNN Context", right_panel_js)
        self.assertIn("isRnnTrainingWorkspaceActive(pageId)", page_guards_js)
        self.assertIn("section.style.display = \"none\";", page_guards_js)
        self.assertIn("function isRnnRegressionMetrics", training_js)
        self.assertIn('isRegression ? "MAE" : "Accuracy"', training_js)
        self.assertIn('isRegression ? "Regression" : "Classification"', training_js)

    def test_rnn_evaluation_layout_has_vertical_chart_and_scroll_table_rules(self):
        style_css = (ROOT / "static" / "styles" / "pages" / "rnn_training.css").read_text(encoding="utf-8")

        self.assertIn(".rnn-eval-flow", style_css)
        self.assertIn("grid-template-columns: minmax(0, 1fr);", style_css)
        self.assertIn(".rnn-eval-chart-stack", style_css)
        self.assertIn(".rnn-baseline-note", style_css)
        self.assertIn(".rnn-compare-mini-chart", style_css)
        self.assertIn(".rnn-compare-metric-toggle", style_css)
        self.assertIn(".rnn-compare-mini-row", style_css)
        self.assertIn(".rnn-compare-mini-row.is-missing", style_css)
        self.assertIn(".rnn-training-layout", style_css)
        self.assertIn(".rnn-training-secondary-grid", style_css)
        self.assertIn(".rnn-output-handoff-grid", style_css)
        self.assertIn("@media (max-width: 840px)", style_css)
        self.assertIn(".rnn-training-config-section", style_css)
        self.assertIn(".rnn-custom-model-section", style_css)
        self.assertIn("grid-template-columns: minmax(0, 1fr);", style_css)
        self.assertIn(".rnn-readiness-compact-grid", style_css)
        self.assertIn(".rnn-readiness-details", style_css)
        self.assertIn(".rnn-table-scroll-10", style_css)
        self.assertIn("max-height: 452px", style_css)
        self.assertIn("position: sticky", style_css)


if __name__ == "__main__":
    unittest.main()
