import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class UIShellModularizationStaticTests(unittest.TestCase):
    def test_style_shell_delegates_design_tokens_to_styles_module(self):
        style_css = (ROOT / "static" / "style.css").read_text(encoding="utf-8")
        tokens_css = (ROOT / "static" / "styles" / "tokens.css").read_text(encoding="utf-8")
        base_css = (ROOT / "static" / "styles" / "base.css").read_text(encoding="utf-8")
        layout_css = (ROOT / "static" / "styles" / "layout.css").read_text(encoding="utf-8")
        components_css = (ROOT / "static" / "styles" / "components.css").read_text(encoding="utf-8")
        dashboard_css = (ROOT / "static" / "styles" / "pages" / "dashboard.css").read_text(encoding="utf-8")
        augmentation_css = (ROOT / "static" / "styles" / "pages" / "augmentation.css").read_text(encoding="utf-8")
        model_compare_css = (ROOT / "static" / "styles" / "pages" / "model_compare.css").read_text(encoding="utf-8")
        inference_css = (ROOT / "static" / "styles" / "pages" / "inference.css").read_text(encoding="utf-8")

        self.assertTrue(
            style_css.startswith(
                '@import "./styles/tokens.css";\n'
                '@import "./styles/base.css";\n'
                '@import "./styles/layout.css";\n'
                '@import "./styles/components.css";\n'
                '@import "./styles/pages/dashboard.css";\n'
                '@import "./styles/pages/augmentation.css";\n'
                '@import "./styles/pages/model_compare.css";\n'
                '@import "./styles/pages/inference.css";'
            )
        )
        self.assertNotIn(":root {\n  --bg:", style_css)
        self.assertNotIn('body[data-theme="light"] {\n  --bg:', style_css)
        self.assertNotIn("html,\nbody {\n  margin: 0;", style_css)
        self.assertNotIn("button,\ninput,\nselect", style_css)
        self.assertNotIn(".app-shell {", style_css)
        self.assertNotIn(".top-header {", style_css)
        self.assertNotIn(".app-body {", style_css)
        self.assertNotIn(".right-summary-panel {", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.btn \{")
        self.assertNotRegex(style_css, r"(?m)^\.badge \{")
        self.assertNotRegex(style_css, r"(?m)^\.global-progress-hud \{")
        self.assertNotRegex(style_css, r"(?m)^\.guard-stack \{")
        self.assertNotRegex(style_css, r"(?m)^\.narrow-form \{")
        self.assertNotRegex(style_css, r"(?m)^\.form-stack \{")
        self.assertNotRegex(style_css, r"(?m)^\.table-wrap \{")
        self.assertNotRegex(style_css, r"(?m)^\.data-table \{")
        self.assertNotRegex(style_css, r"(?m)^\.modal-overlay \{")
        self.assertNotRegex(style_css, r"(?m)^\.modal-content \{")
        self.assertNotRegex(style_css, r"(?m)^\.toast \{")
        self.assertNotRegex(style_css, r"(?m)^\.summary-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.summary-badge \{")
        self.assertNotRegex(style_css, r"(?m)^\.product-state-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-map-panel \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.workflow-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.augmentation-workspace \{")
        self.assertNotRegex(style_css, r"(?m)^\.augmentation-settings-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.custom-setting-item \{")
        self.assertNotRegex(style_css, r"(?m)^\.preset-item \{")
        self.assertNotRegex(style_css, r"(?m)^\.aug-preview-container \{")
        self.assertNotIn("Physical Augmentation Redesign Styles", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.model-compare-mode-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.compare-mode-row \{")
        self.assertNotRegex(style_css, r"(?m)^\.model-compare-layout \{")
        self.assertNotRegex(style_css, r"(?m)^\.compare-run-card \{")
        self.assertNotRegex(style_css, r"(?m)^\.compare-output-controls \{")
        self.assertNotIn("Model Compare Center", style_css)
        self.assertNotRegex(style_css, r"(?m)^\.inference-lab-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-settings-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-preview-grid \{")
        self.assertNotRegex(style_css, r"(?m)^\.inference-summary-grid \{")
        self.assertRegex(style_css, r"(?m)^\.preview-tile \{")
        self.assertIn(".dashboard-lower-grid,\n.two-column-layout", style_css)
        self.assertIn(".preview-panel {", style_css)
        self.assertIn("@media (max-width: 840px) {", style_css)

        self.assertIn(":root {", tokens_css)
        self.assertIn("--bg: #0f1318;", tokens_css)
        self.assertIn("--primary: #3b82f6;", tokens_css)
        self.assertIn("--radius: 8px;", tokens_css)
        self.assertIn('body[data-theme="light"] {', tokens_css)
        self.assertIn("--shadow: 0 12px 30px rgba(15, 23, 42, 0.12);", tokens_css)

        self.assertIn("* {\n  box-sizing: border-box;", base_css)
        self.assertIn("html,\nbody {\n  margin: 0;", base_css)
        self.assertIn('font-family: "Inter", "Microsoft JhengHei", "PingFang TC", sans-serif;', base_css)
        self.assertIn("button,\ninput,\nselect", base_css)
        self.assertIn("code {", base_css)
        self.assertNotIn(".app-shell {", base_css)

        self.assertIn(".app-shell {", layout_css)
        self.assertIn("grid-template-rows: 64px 1fr;", layout_css)
        self.assertIn(".top-header {", layout_css)
        self.assertIn(".app-body {", layout_css)
        self.assertIn("grid-template-columns: 250px minmax(0, 1fr) 300px;", layout_css)
        self.assertIn(".sidebar {", layout_css)
        self.assertIn(".main-content {", layout_css)
        self.assertIn(".right-summary-panel {", layout_css)
        self.assertIn(".page-header {", layout_css)
        self.assertNotIn(".btn {", layout_css)

        self.assertRegex(components_css, r"(?m)^\.btn \{")
        self.assertRegex(components_css, r"(?m)^\.icon-btn \{")
        self.assertIn(".panel-section,\n.summary-section,\n.control-card,\n.metric-card,\n.status-guard", components_css)
        self.assertRegex(components_css, r"(?m)^\.badge \{")
        self.assertRegex(components_css, r"(?m)^\.global-progress-hud \{")
        self.assertIn("@keyframes progress-hud-pending", components_css)
        self.assertRegex(components_css, r"(?m)^\.guard-stack \{")
        self.assertRegex(components_css, r"(?m)^\.guard-next-actions \{")
        self.assertRegex(components_css, r"(?m)^\.narrow-form \{")
        self.assertRegex(components_css, r"(?m)^\.form-stack \{")
        self.assertIn('input[type="text"],\ninput[type="number"],\nselect {', components_css)
        self.assertRegex(components_css, r"(?m)^\.table-wrap \{")
        self.assertRegex(components_css, r"(?m)^\.data-table \{")
        self.assertRegex(components_css, r"(?m)^\.modal-overlay \{")
        self.assertRegex(components_css, r"(?m)^\.modal-content \{")
        self.assertRegex(components_css, r"(?m)^\.toast \{")
        self.assertRegex(components_css, r"(?m)^\.summary-row \{")
        self.assertRegex(components_css, r"(?m)^\.summary-badge \{")
        self.assertRegex(components_css, r"(?m)^\.product-state-card \{")
        self.assertNotIn(".dashboard-lower-grid,\n.two-column-layout", components_css)
        self.assertNotRegex(components_css, r"(?m)^\.workflow-card \{")
        self.assertNotRegex(components_css, r"(?m)^\.augmentation-workspace \{")

        self.assertRegex(dashboard_css, r"(?m)^#page-dashboard \.dashboard-lower-grid \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-map-panel \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-map-title \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-grid \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-card \{")
        self.assertRegex(dashboard_css, r"(?m)^\.workflow-row \{")
        self.assertIn("@media (max-width: 1500px) {", dashboard_css)
        self.assertIn("@media (max-width: 1180px) {", dashboard_css)

        self.assertRegex(augmentation_css, r"(?m)^\.augmentation-workspace \{")
        self.assertRegex(augmentation_css, r"(?m)^\.augmentation-settings-layout \{")
        self.assertRegex(augmentation_css, r"(?m)^\.custom-setting-item \{")
        self.assertRegex(augmentation_css, r"(?m)^\.preset-item \{")
        self.assertRegex(augmentation_css, r"(?m)^\.aug-preview-container \{")
        self.assertIn("Physical Augmentation Redesign Styles", augmentation_css)
        self.assertIn("@media (max-width: 840px) {", augmentation_css)

        self.assertIn("Model Compare Center", model_compare_css)
        self.assertRegex(model_compare_css, r"(?m)^\.model-compare-mode-card \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-mode-row \{")
        self.assertRegex(model_compare_css, r"(?m)^\.model-compare-layout \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-run-card \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-output-controls \{")
        self.assertRegex(model_compare_css, r"(?m)^\.compare-report-history-card \{")
        self.assertIn("@media (max-width: 840px) {", model_compare_css)

        self.assertRegex(inference_css, r"(?m)^\.inference-lab-grid \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-settings-grid \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-toggle-row \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-result-panel \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-preview-grid \{")
        self.assertRegex(inference_css, r"(?m)^\.inference-summary-grid \{")
        self.assertNotRegex(inference_css, r"(?m)^\.preview-tile \{")
        self.assertIn("@media (max-width: 840px) {", inference_css)

    def test_state_shell_delegates_i18n_dictionary_and_fallback_to_state_module(self):
        state_js = (ROOT / "static" / "state.js").read_text(encoding="utf-8")
        i18n_js = (ROOT / "static" / "state" / "i18n.js").read_text(encoding="utf-8")

        self.assertIn('from "./state/i18n.js"', state_js)
        self.assertIn('export { i18n } from "./state/i18n.js";', state_js)
        self.assertIn("return translateI18n(key, appState.settings.language, params);", state_js)
        self.assertIn("applyLanguageToDocument({", state_js)
        self.assertNotIn("export const i18n = {", state_js)
        self.assertNotIn("let zhFallbackObserver", state_js)
        self.assertNotIn("configureI18nFallback", state_js)

        self.assertIn("export const i18n = {", i18n_js)
        self.assertIn("export function translate", i18n_js)
        self.assertIn("export function applyLanguageToDocument", i18n_js)
        self.assertIn("let zhFallbackObserver", i18n_js)
        self.assertIn("configureI18nFallback", i18n_js)

    def test_app_shell_delegates_common_shell_rendering_to_core_modules(self):
        app_js = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
        header_js = (ROOT / "static" / "core" / "header_status.js").read_text(encoding="utf-8")
        guards_js = (ROOT / "static" / "core" / "page_guards.js").read_text(encoding="utf-8")
        availability_js = (ROOT / "static" / "core" / "action_availability.js").read_text(encoding="utf-8")
        toast_js = (ROOT / "static" / "core" / "toast.js").read_text(encoding="utf-8")
        router_js = (ROOT / "static" / "core" / "router.js").read_text(encoding="utf-8")
        right_panel_js = (ROOT / "static" / "core" / "right_panel.js").read_text(encoding="utf-8")
        page_registry_js = (ROOT / "static" / "core" / "page_registry.js").read_text(encoding="utf-8")
        tooltip_js = (ROOT / "static" / "core" / "tooltip.js").read_text(encoding="utf-8")
        project_lifecycle_js = (ROOT / "static" / "core" / "project_lifecycle.js").read_text(encoding="utf-8")

        self.assertIn('from "./core/header_status.js"', app_js)
        self.assertIn('from "./core/page_guards.js"', app_js)
        self.assertIn('from "./core/action_availability.js"', app_js)
        self.assertIn('from "./core/toast.js"', app_js)
        self.assertIn('from "./core/router.js"', app_js)
        self.assertIn('from "./core/right_panel.js"', app_js)
        self.assertIn('from "./core/tooltip.js"', app_js)
        self.assertIn('from "./core/project_lifecycle.js"', app_js)
        self.assertIn('from "./core/page_registry.js"', app_js)
        self.assertIn("createProjectLifecycle({ renderAll, navigate });", app_js)
        self.assertIn("initPageModules();", app_js)
        self.assertIn("initInfoTooltips();", app_js)
        self.assertIn("renderHeaderStatusCore();", app_js)
        self.assertIn("renderPrimaryPageModules(status);", app_js)
        self.assertIn("renderRightPanelCore(appState.currentPage, status);", app_js)
        self.assertIn("renderPageGuardsCore(appState.currentPage, status);", app_js)
        self.assertIn("renderSecondaryPageModules(status);", app_js)
        self.assertIn("updateActionAvailabilityCore(status);", app_js)
        self.assertIn("showToastCore(message);", app_js)
        self.assertIn("setActivePage(pageId);", app_js)
        self.assertNotIn('from "./pages/dashboard.js"', app_js)
        self.assertNotIn('from "./pages/training.js', app_js)
        self.assertNotIn("async function bootstrapSession", app_js)
        self.assertNotIn("async function loadProjects", app_js)
        self.assertNotIn("async function openProject", app_js)
        self.assertNotIn("async function saveCurrentProject", app_js)
        self.assertNotIn("async function requestProjectSave", app_js)
        self.assertNotIn("async function checkCurrentTrainStatus", app_js)
        self.assertNotIn("function renderHeaderStatus()", app_js)
        self.assertNotIn("function renderRightPanel(pageId, status)", app_js)
        self.assertNotIn("const RIGHT_PANEL_CONFIG", app_js)
        self.assertNotIn("function renderPageGuards(pageId, status)", app_js)
        self.assertNotIn("function updateActionAvailability(status)", app_js)
        self.assertNotIn("function showToast(message)", app_js)
        self.assertNotIn("function bindInfoTooltips()", app_js)
        self.assertNotIn("renderTooltipContent", app_js)

        self.assertIn("export function renderHeaderStatus", header_js)
        self.assertIn("#header-gpu-value", header_js)
        self.assertIn("#header-project-title", header_js)

        self.assertIn("export function renderPageGuards", guards_js)
        self.assertIn("isRnnTrainingWorkspaceActive(pageId)", guards_js)
        self.assertIn("Training blocked", guards_js)

        self.assertIn("export function updateActionAvailability", availability_js)
        self.assertIn('qsa(".guarded")', availability_js)
        self.assertIn("#btn-start-train", availability_js)

        self.assertIn("export function showToast", toast_js)
        self.assertIn("#toast", toast_js)
        self.assertIn("window.setTimeout", toast_js)

        self.assertIn("export function setActivePage", router_js)
        self.assertIn('qsa(".sidebar-item")', router_js)
        self.assertIn('qsa(".page")', router_js)
        self.assertIn('pageId || "dashboard"', router_js)

        self.assertIn("export function renderRightPanel", right_panel_js)
        self.assertIn("const RIGHT_PANEL_CONFIG", right_panel_js)
        self.assertIn("function buildRnnTrainingRightPanel", right_panel_js)
        self.assertIn("RNN Context", right_panel_js)

        self.assertIn("export function initPageModules", page_registry_js)
        self.assertIn("export function renderPrimaryPageModules", page_registry_js)
        self.assertIn("export function renderSecondaryPageModules", page_registry_js)
        self.assertIn("export function syncPageModeForProject", page_registry_js)
        self.assertIn("export function loadPageRecommendedConfig", page_registry_js)
        self.assertIn("renderDashboard(status);", page_registry_js)
        self.assertIn("renderTrainingWorkspace();", page_registry_js)

        self.assertIn("export function initInfoTooltips", tooltip_js)
        self.assertIn("#floating-tooltip", tooltip_js)
        self.assertIn(".info-icon[data-tooltip]", tooltip_js)
        self.assertIn("escapeHtml", tooltip_js)
        self.assertIn('window.addEventListener("resize"', tooltip_js)

        self.assertIn("export function createProjectLifecycle", project_lifecycle_js)
        self.assertIn("async function bootstrapSession", project_lifecycle_js)
        self.assertIn("async function loadProjects", project_lifecycle_js)
        self.assertIn("async function openProject", project_lifecycle_js)
        self.assertIn("async function saveCurrentProject", project_lifecycle_js)
        self.assertIn("async function requestProjectSave", project_lifecycle_js)
        self.assertIn("async function checkCurrentTrainStatus", project_lifecycle_js)
        self.assertIn("showToastCore(`Failed to load projects: ${err.message}`);", project_lifecycle_js)
        self.assertIn("syncPageModeForProject(appState.currentProject", project_lifecycle_js)
        self.assertIn("await loadPageRecommendedConfig();", project_lifecycle_js)
        self.assertIn("clearDeletedProject", project_lifecycle_js)


if __name__ == "__main__":
    unittest.main()
