"""Generate the deliberately scoped frontend API declarations from OpenAPI."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app import app  # noqa: E402


OUTPUT = ROOT / "static" / "generated" / "api-types.d.ts"
SCOPED = ("ProjectResponse", "TrainingReadinessBlocker", "TrainingReadinessResponse")


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "object": "Record<string, unknown>", "null": "null"}.get(kind, "unknown")


def render() -> str:
    schemas = app.openapi().get("components", {}).get("schemas", {})
    lines = ["// Generated by tools/generate_frontend_api_types.py. Do not edit.", ""]
    for name in SCOPED:
        schema = schemas.get(name, {})
        required = set(schema.get("required", []))
        lines.append(f"export interface {name} {{")
        for field, field_schema in schema.get("properties", {}).items():
            lines.append(f"  {field}{'' if field in required else '?'}: {ts_type(field_schema)};")
        lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print("Generated API types are out of date. Run tools/generate_frontend_api_types.py")
            return 1
        print("Generated API types are current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
